config/routes.rb
Cs169Project::Application.routes.draw do
  get "/search" => 'pubmed#search'

  root :to => 'pubmed#index'
  
  match "/auth/:provider/callback" => "sessions#create"

  get "/auth/failure" do
    flash[:notice] = params[:message]
    redirect '/'
  end

  match "/signout" => "sessions#destroy", :as => :signout
  match "/preference" => "user#preference", :as => :preference
  match "/user/save_article" => "user#save_article",:as => :save_article
  match "/user/unsave_article" => "user#unsave_article", :as => :unsave_article
  
  match "/user/saved_articles" => "user#saved_articles", :as => :saved_articles
  match "/user/delete_article" => "user#delete_article", :as => :delete_article

  match "/user/add_preference" => "user#add_preference", :via => :post

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :saved_articles
  validates_uniqueness_of :pubmed_id


end

app/models/identity.rb
class Identity < ActiveRecord::Base
end

app/models/journal.rb
class Journal < ActiveRecord::Base

  def self.impact(isoabbrev)
    Journal.find(:all).each do |j|
      if j.iso == isoabbrev
        return j.impact
      end
    end
    return 0
  end

end

app/models/saved_article.rb
class SavedArticle < ActiveRecord::Base

  belongs_to :user
  belongs_to :article 

  validates :user_id, :presence => true,
            :uniqueness => {:scope => [:article_id], :message => "article is already saved."}
  validates :article_id, :presence => true,
            :uniqueness => {:scope => [:user_id], :message => "article is already saved."}


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :saved_articles

  def saved?(pubmed_article_id)
    if not (article_id = Article.find_by_pubmed_id(pubmed_article_id))
      return false
    end
    if self.saved_articles.exists?(:article_id => article_id, :user_id =>self.id)
      return true
    else
      return false
    end
  end

  def get_preference()
		return self.preference
  end


  def add_preference(preference)
		self.update_attributes(:preference => preference)
  end

  def save_article(pubmed_article_id, article_title)
    #logger.info("inside model save_article")
    if not (article = Article.find_by_pubmed_id(pubmed_article_id))
      article = Article.create(:pubmed_id => pubmed_article_id, :title => article_title)
      #logger.info("created article")
      #logger.info(article)
    end
    saved_article = SavedArticle.create(:article_id => article.id, :user_id => self.id)
    #logger.info("Created saved_article")
    #logger.info(saved_article)
    return
  end

  def unsave_article(pubmed_article_id)
    #logger.info("inside model unsave_article")
    article_id = Article.find_by_pubmed_id(pubmed_article_id)
    article = SavedArticle.where("article_id = ? AND user_id = ?", article_id, self.id)
    if article.size > 0
     	article[0].destroy
    	#logger.info("Unsaved article")
    end
    return
  end

  def delete_article(article_id)
    #logger.info("inside model delete_article")
    article = SavedArticle.where("article_id = ? AND user_id = ?", article_id, self.id)
    if article.size > 0
    	article[0].destroy
	    #logger.info("Deleted article")
    end
    return
  end

  def get_saved_articles()
    #logger.info(self.id)
    articles = self.saved_articles
    #logger.info(articles)
    return articles
  end

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pubmed_controller.rb
class PubmedController < ApplicationController
  include PubmedHelper
  
  def index
    session[:search_term] = nil
    render 'search'
  end
  
  def requestPubmed(search_query)
    PubmedSearch.search(search_query)
  end
  
  def parseArticles(articleIDList, parameters)
    ArticleXMLParser.new(articleIDList, parameters)
  end

  def search
    if params[:search_term].blank?
	flash[:notice] = "Please input a search term"
	session[:search_term] = nil
	redirect_to root_path
	return
    end
    connector = 'AND'
    medical_field = nil
    if current_user
      if not current_user.preference.nil?
        medical_field = current_user.preference
      end
    end
    if medical_field.nil? or medical_field.empty?
    	search_query = params[:search_term]
    else
	    search_query = "(" + params[:search_term] + ") " + connector + " " + medical_field + "[MeSH Terms]"
    end
    #puts "Search query is " + search_query
    search_results = requestPubmed(search_query)    
    @articleIDList = search_results.pmids
    @results = parseArticles(@articleIDList, params[:search_term])
    @current_results = Array.new
    @results.each do |result|
      @current_results.push(result)
    end
    @current_results = Kaminari::PaginatableArray.new(@current_results).page(params[:page]).per(10)
    session[:search_term] = params[:search_term]

    render 'results'

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def save_article
    #logger.info("inside controller saving article")
    #logger.info(params[:article_id])
    current_user.save_article(params[:article_id], params[:article_title])
    if (params[:js] == 1)
      render :nothing => true
    else
      redirect_to saved_articles_path
    end
  end


  def unsave_article
    #logger.info("inside controller unsaving article")
    current_user.unsave_article(params[:article_id])
    if (params[:js] == 1)
      render :nothing => true
    else
      redirect_to saved_articles_path
    end
  end

  def delete_article
    #logger.info("inside controller delete article")
    current_user.delete_article(params[:article_id])
    if (current_user.get_saved_articles().size > 0) and (params[:js] == 1)
      #logger.info("there are saved articles")
      render :nothing => true
    else
      #logger.info("redirecting to saved articles")
      redirect_to saved_articles_path
    end
  end

  def saved_articles
    @saved_articles = []
    articles = current_user.get_saved_articles()
    articles.each do |article|
      @saved_articles << Article.find(article.article_id)
    end

  end

  def preference
    @saved_preference = current_user.get_preference()
		render 'preference'
  end

  def add_preference
    current_user.add_preference(params[:preference])
    redirect_to preference_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drufus</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="/assets/logo-bar.png">
 
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notlogged/default.html.haml
%h1 Search PubMed's database
=form_tag '/search', :method => :put do

  = label :search_label, :search_label, 'Input your search term:'
  = text_field :search_term, 'Search term:'
  
  = label :major_topic, :major_topic, 'Input major topic:'
  = text_field :major_topic_term, 'Major topic term:'

  = label :subheading, :subheading, 'Input subheading:'
  = text_field :subheading_term, 'Subheading term:'

  = label :terms, :terms, 'Input terms'
  = text_field :terms, 'Mesh terms:'

  = submit_tag 'Search!'

app/views/pubmed/_google.html.erb
<div id="user_nav">
  <% if current_user %>
    Welcome, <%= current_user.name %>!
    <%= link_to "Sign Out", signout_path %>
    <br>
    <%= link_to "Saved Articles", saved_articles_path %>
    <br>
    <%= link_to "Search Preference", preference_path %>
  <% else %>
    <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
  <% end %>
</div>

app/views/pubmed/results.html.haml
.content
  = render :partial => 'google'
  = render :partial => 'search_box'
  %br
  %br

  -if @current_results.length == 0
    %p{:align =>'center'} "No results found."
  -@current_results.each_with_index do |result|
    %div{:class => 'article'}
      %p{:class => 'article_title'}=link_to result.title, "http://www.ncbi.nlm.nih.gov/pubmed/#{result.id.to_s}"
      %p{:class => 'publish_date'}='Publication Date: ' + result.date
      %p{:class => 'publish_date'}='Journal: ' + result.journal
      %p{:class => 'article_abstract'}='Abstract: ' + result.abstract
      -if current_user
        -if current_user.saved?(result.id)
          =link_to "Unsave Article", unsave_article_path(:article_id => result.id, :js => 0, :article_title => result.title), :class=> "unsave-article", :article_id => result.id, :article_title => result.title, :id => "article#{result.id.to_s}"
        -else
          =link_to "Save Article", save_article_path(:article_id => result.id, :js => 0, :article_title => result.title), :class=> "save-article", :article_id => result.id, :article_title => result.title, :id => "article#{result.id.to_s}"
      %br
      %br
=paginate @current_results

app/views/pubmed/search.html.haml
.content
  = render :partial => 'google'
  = render :partial => 'search_box'

app/views/user/_google.html.erb
<div id="user_nav">
  <% if current_user %>
    Welcome, <%= current_user.name %>!
    <%= link_to "Sign Out", signout_path %>
    <br>
    <%= link_to "Saved Articles", saved_articles_path %>
    <br>
    <%= link_to "Search Preference", preference_path %>
  <% else %>
    <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
  <% end %>
</div>

app/views/user/_search_box.haml
.search_box
  %h1 Search PubMed's database
  =form_tag '/search', :method => :get do

    = label :search_label, :search_label, 'Input your search term:'
    = text_field '', :search_term, :value => session[:search_term] ? session[:search_term] : ''
    %br
    %br
    = submit_tag 'Search!'
    %br
    %br
    - if flash[:notice]
      .notice 
        = flash[:notice]

app/views/user/preference.html.haml
.content
  = render :partial => 'google'
  = render :partial => 'search_box'
  %br
  %br

  %h2="Preference Page"
  -if @saved_preference.nil? or @saved_preference.empty?
    %h4="You do not have saved preference"
  -else
    %h4="Your saved preference is:" + @saved_preference
  =form_tag '/user/add_preference', :method => :post do
    =label :preferences, :preferences, "Input your preference here: "
    =text_field '', :preference, :value => @saved_preference
    %br
    %br
    =submit_tag "Save Preference"

app/views/user/saved_articles.html.haml
.content
  = render :partial => 'google'
  = render :partial => 'search_box'
  %br
  %br
  %h2 Saved Articles
  -if @saved_articles.nil? or @saved_articles.length == 0
    %p{:align =>'center'} "No saved articles."
  -@saved_articles.each do |result|
    %div{:class => 'article'}
      %p{:class => 'article_title'}=link_to result.title, "http://www.ncbi.nlm.nih.gov/pubmed/#{result.id.to_s}"
      =link_to "Delete Article", delete_article_path(:article_id => result.id, :js => 0), :class=> "delete-article", :article_id => result.id, :id => "article#{result.id.to_s}"

      %br
      %br